{"level":"error","message":"Unable to connect to the database: ������������ \"clixxx_user\" �� ������ �������� ����������� (�� ������)","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":123,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"parent":{"code":"28P01","file":"auth.c","length":123,"line":"324","name":"error","routine":"auth_failed","severity":"�����"},"stack":"SequelizeConnectionError: ������������ \"clixxx_user\" �� ������ �������� ����������� (�� ������)\n    at Client._connectionCallback (C:\\Users\\user\\monorepo\\backend-js\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\user\\monorepo\\backend-js\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\user\\monorepo\\backend-js\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\user\\monorepo\\backend-js\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\user\\monorepo\\backend-js\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\user\\monorepo\\backend-js\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-08-10 13:38:51:3851"}
